server.modules += ("mod_cgi")

$SERVER["socket"] == ":8080" {
    server.document-root = "/opt/dyndns/web/static"
    index-file.names = ("index.html")

    alias.url = (
        "/cgi-bin/" => "/opt/dyndns/web/cgi-bin/",
        "/peer/"    => "/opt/dyndns/web/peer-cgi/"
    )

    cgi.assign = (".py" => "/usr/bin/python3")

    mimetype.assign = (
        ".html" => "text/html; charset=utf-8",
        ".css"  => "text/css; charset=utf-8",
        ".js"   => "application/javascript; charset=utf-8",
        ".svg"  => "image/svg+xml",
        ".json" => "application/json"
    )
}
